### ISSUE TITLE
Change default parinfer-rust-mode-map key bindings

### ISSUE THREAD

**Issue by dannyfreeman** [justinbarclay/parinfer-smart-mode#62]
The default keybindings for parinfer-rust-mode clash with some major mode bindings. One of those modes is Cider. Parinfer-rust-mode pairs very well with Cider so they are often active at the same time. The clashing key is `C-c C-p` bound to `cider-pprint-eval-last-sexp`.

According to the [Emacs key binding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) 

> Sequences consisting of C-c followed by a control character or a digit are reserved for major modes

which includes `C-c C-p`. 

`C-c` followed by a letter are reserved for users, which leaves

> Sequences consisting of C-c followed by any other ASCII punctuation or symbol character are allocated for minor modes

If parinfer-rust-mode _must_ have some keys bound out of the box by default, then consider changing them to follow these Emacs conventions. Maybe something like `C-c C-(` would be fine and easy to remember. Another option is to not bind them at all, leaving the `parinfer-rust-mode-map` empty for users to bind to as they please.

**Comment by justinbarclay** [comment]
Yeah, that makes sense. I don't think I realized I was abusing the conventions when writing this. I'd be happy to take a PR that disables the bindings and adds docs pointing users on how to enable them (preferably to the current bindings).
